{
 "title": "Summary dashboard",
 "description": "Dashboard to monitor GC pause time across multiple jobs in .NET with specific colors.",
 "tags": [
  "dotnet",
  "garbage collection",
  "system.runtime"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(dotnet_gc_pause_time_seconds_total, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Container CPU user seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(name) (irate(container_cpu_user_seconds_total{name=~\"benchmark_webapp_aot|benchmark_webapp_no_aot\",image!=\"\"}[5m]) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name) (\r\n    container_memory_usage_bytes{name=~\"benchmark_webapp_aot|benchmark_webapp_no_aot\", image!=\"\"}\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (testid)(irate(k6_http_reqs_total{testid=~'$job'}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC Pause Time Total",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "seconds" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(dotnet_gc_pause_time_seconds_total{job=~'$job'})",
     "legendFormat": "{{job}} - GC Pause Time Total"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "GC Heap Total Allocated",
   "type": "timeseries",
   "description": "The approximate number of bytes allocated on the managed GC heap since the process has started. The returned value does not include any native allocations",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "dotnet_gc_heap_total_allocated_bytes_total{ job=~'$job'}",
     "legendFormat": "{{job}} "
    }
   ]
  },
  {
   "title": "GC Pause Time Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "seconds" } },
   "targets": [
    {
     "expr": "(dotnet_gc_pause_time_seconds_total{job=~'$job'})",
     "legendFormat": "{{job}} - GC Pause Time Total"
    }
   ]
  },
  {
   "title": "GC Collections Total by Generation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "count" } },
   "targets": [
    {
     "expr": "sum by(gc_heap_generation, job)(dotnet_gc_collections_total{job=~'$job'})",
     "legendFormat": "{{job}} - GC Generation {{gc_heap_generation}}"
    }
   ]
  },
  {
   "title": "GC Last Collection Heap Size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(job, gc_heap_generation)(dotnet_gc_last_collection_heap_size_bytes{ job=~'$job'})",
     "legendFormat": "{{job}} GEN {{gc_heap_generation)}"
    }
   ]
  },
  {
   "title": "Thread Pool Thread Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum by(job)(dotnet_thread_pool_thread_count_total{job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Working Set",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(job)(dotnet_process_memory_working_set_bytes{ job=~'$job'})",
     "legendFormat": "{{job}} "
    }
   ]
  }
 ]
}